<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samovar.Grid.WebAppWasmTest.Client\Samovar.Grid.WebAppWasmTest.Client.csproj" />
    <ProjectReference Include="..\..\Samovar.Grid.TestPages\Samovar.Grid.TestPages.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

</Project>
