<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Samovar.Grid\Samovar.Grid.csproj" />
    <ProjectReference Include="..\Samovar.Grid.WebAppAutoTest.Client\Samovar.Grid.WebAppAutoTest.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server"  />
  </ItemGroup>

</Project>
